### ISSUE TITLE
Mouse sensitivity bar is reversed

### ISSUE THREAD

**Issue by SethDusek** [linuxmint/cinnamon-settings-daemon#133]
So this is something that is either a bug or a really bad design choice but this ![](http://i.shibe.ml/QmVskbbEggKLPEzFLHCSBMW7MeGFts8hzqQkPL3SPvunU2.png) is what the sensitivity bar looks like in the mouse section of cinnamon-settings. If you can't notice what's wrong, the bar is reversed. It's going from High->Low instead of Low->High

**Comment by JosephMcc** [comment]
This is actually part of our main cinnamon package, not cinnamon-settings-daemon. It's also known and already on out Roadmap to be fixed. It's a weird behavior of that GtkSlider when using certain types of values and we just need to add a way to work around it.

Since this isn't really the right place and we know about this one, I'm going to go ahead and close this.
