### ISSUE TITLE
Mouse pointer theme is stuck 

### ISSUE THREAD

**Issue by ACinnamonUserInUK** [linuxmint/cinnamon-settings-daemon#176]
After installing the 18.2 beta, I switched between mouse themes and now my system is stuck on one particular mouse theme; whatever I do, it seems I cannot switch back. 

PS: I don't know whether this is the right place to report this error. If one is not deeply immersed in Mint, it is hard - I think it is fair to say - to know which repository (or sub-repository) to file bug reports in.

**Comment by JosephMcc** [comment]
I don't know what you are running but there is no Mint18.2 beta.

**Comment by ACinnamonUserInUK** [comment]
I am running Cinnamon 3.4, which is, I am given to understand, being tested at present and will be part of Mint 18.2. (Hence, 'Mint 18.2 beta.) See e.g. and esp. here: 
https://www.reddit.com/r/linuxmint/comments/6a7j70/cinnamon_34_released_two_weeks_of_testing_til_182/

**Comment by JosephMcc** [comment]
Ok. Well Cinnamon releases and Mint betas are two totally different things. Without accurate info bugs reports are essentially worthless. I assume you are actually running Mint 18.1 with Cinnamon you installed from somewhere. Where/how matters. Especially since changing mouse cursors works perfectly fine here.

On top of that, after reading the reddit post, don't base things on random info that doesn't officially come from Mint. That is nothing more than people talking out of there you know what.

**Comment by leigh123linux** [comment]
Changing mouse cursors works on fedora.

**Comment by ACinnamonUserInUK** [comment]
JosephMcc, leigh123linux: thank you for the informative responses.

I was running Mint 18.1 (64-bit) with a version of Cinnamon 3.4 that I obtained via a PPA mentioned on the Reddit thread that I cited. However, I have now reverted back to Cinnamon 3.2.7 (and so I am afraid that I cannot give you details of the packages that I was running).
