### ISSUE TITLE
Request: Separete Tiling and Snapping

### ISSUE THREAD

**Issue by Fjodor42** [linuxmint/cinnamon-settings-daemon#185]
Basically, I would like to disable tiling, while still having snapping enabled.

CSD UI suggests that this isn't currently possible, but didn't it use to be?

**Comment by mtwebster** [comment]
In case you mean the old 'snap' behavior (holding shift while dragging a window), you can enable it:

```
gsettings set org.cinnamon.muffin legacy-snap true
```

Otherwise, you can't have what we currently call 'snapping' without tiling (and have never been able to.)

I think legacy-snap was more or less incompatible with the new style, so be sure to disable tiling thru cinnamon-settings if you try it.

**Comment by Fjodor42** [comment]
Well, even with "Tiling and Snapping" disabled, there seems to be a small amount of "guidance resistance", which was what I assumed was "Snapping", but is actually what I want - "Tiling and Snapping" thus disabled.

Thank you for clarifying!

**Comment by mtwebster** [comment]
Ah we call that 'edge resistance' ;)
